services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FIAP_ADJT
      POSTGRES_DB: cadastra_restaurante_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-restaurante-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cadastra_restaurante_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: FIAP_ADJT

volumes:
  postgres-restaurante-data:
